import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import { useSession, signIn, signOut } from 'next-auth/react'

import { logDev } from '../utils/'

import Link from 'next/link'

export default function Home () {
  const { data: session, status } = useSession()

  if (status === 'authenticated') {
    const exp = new Date()
    exp.setHours(8)
    if (session) { session.expires = exp.getTime().toString() }
  }

  return (
    <div className={styles.container}>
      <Head>
        <>
          <Script
            src="https://example.com/script.js"
            onLoad={() => {
              logDev('Script has loaded')
            }}
          />
        </>
        <title>OnBoarding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="main" className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <button onClick={() => {
          signIn('google')
        }} className="mt-3 h-10 w-[12rem] rounded-xl bg-green-700 text-white">
          Singin GOOGLE
        </button>

        <button onClick={() => {
          signIn('github')
        }} className="mt-3 h-10 w-[12rem] rounded-xl bg-green-700 text-white">
          Singin GIT-HUB
        </button>

        <Link href="/api/auth/signout">
          <button onClick={(e) => {
            e.preventDefault()
            logDev('event signOut: ', e)
            signOut()
          }} className="mt-3 h-10 w-[12rem] rounded-xl bg-red-700 text-white">
            singout
          </button>
        </Link>
        <Link href="/signup">
          Signup
        </Link>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
